name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    name: Build Static Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          cache: true

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build Static Site
        run: bun x nuxt build --preset github_pages

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: .output/public

  deploy:
    name: Deploy Site
    needs:
      - build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4